# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 56cdffcaf63fead100819458b8a643118cb1c5cfc8db72460be8d92e0f83572c6d23f96d9bb2934232ae16aa7426b378049852ae7168e64e4e99733e5ab68b45

test:
  secret_key_base: d1e98282fe21d4cc0030e92ba6f62e754f4ee042c1149d5790cf76c79a3f176ac5fc81c294f83bc8f0a3768212e9983732e94c79244944ab9c030498c3e29719

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
